#!/usr/bin/env bash
file_in="test_in_small.txt"
file_out="test_out_small.txt"
program_out="tmp_out"
compare_out="tmp_cmp"

total_line=`grep -c ".*" $file_in`

#make sure binary is up-to-date
make
#run and compare
cat $file_in | ./final_project > $program_out
processed_line=`grep -c ".*" $program_out`
diff $file_out $program_out > $compare_out
diff_line=`head -n 1 $compare_out | awk -F [,c] '{print $1}'`

echo -e "\n\n\n"

#different
if [ "$diff_line" ] ;then
    echo -e "difference found in line $diff_line"
    echo "command:"
    sed -n "${diff_line}p" $file_in
    echo -e "----------------------------------------------------------"
    echo -e "correct output:"
    sed -n "${diff_line}p" $file_out
    echo -e "----------------------------------------------------------"
    echo -e "now output:"
    sed -n "${diff_line}p" $program_out
#identical
else
    echo -e "all correct"
fi
#judge if runtime error
if [ $processed_line -ne $total_line ] ;then
    echo -e "----------------------------------------------------------"
    echo -e "segmentation fault at line $processed_line, command:"
    sed -n "${diff_line}p" $file_in
fi

rm -f $program_out $compare_out
